/*
 * test.cpp
 */

#include <iostream>
#include <stdexcept>

/*
int main() {
	try {
	} catch(const std::exception& e) {
		std::cerr << e.what() << '\n';
	} catch(...) {
		return -1;
	}
}
*/


